version: '3'

services:
  meshcentral: 
    container_name: meshcentral_main
    image: "naim/meshcentral-docker"
    build: "."
    restart: "unless-stopped"
    volumes:
      - "./app/meshcentral/meshcentral-data:/opt/meshcentral/meshcentral-data"
      - "./app/meshcentral/meshcentral-files:/opt/meshcentral/meshcentral-files"
      - "./app/meshcentral/meshcentral-backup:/opt/meshcentral/backup"
    ports: 
      - "8181:8181"
      - "4333:4333"
    networks:
      - meshcentral_network

  mongodb:
    container_name: meshcentral_db
    image: "mongo"
      #    command: "--serviceExecutor adaptive"
    restart: "unless-stopped"
    volumes:
      #      - "./app/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./app/mongodb/mongodb-data:/data/db"
      - "./app/mongodb/mongodb-config:/data/configdb"
        #    env_file:
        #      - "./app/mongodb.env"
    networks:
      - meshcentral_network

networks:
  meshcentral_network:
